#!/bin/bash
# Created by http://www.embex.online
# Modified by 0123456
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to Server..."
sleep 0.4
echo "Checking Permision..."
sleep 0.3
CEK=0123456
if [ "$CEK" != "0123456" ]; then
		echo -e "${red}Permission Denied!${NC}";
        echo $CEK;
        exit 0;
else
echo -e "${green}Permission Accepted...${NC}"
sleep 1
clear
fi

IP=$(wget -qO- ipv4.icanhazip.com)
read -p "How many accounts will be created?: " banyakuser
read -p "How many days?                    : " aktif
today="$(date +"%Y-%m-%d")"
expire=$(date -d "$aktif days" +"%Y-%m-%d")
clear
echo " "
echo " "
echo " "
echo "-----------------------------------"
echo "        Account Information        "
echo "-----------------------------------"
echo "   - OpenSSH                 : 22"
echo "   - OpenVPN                 : TCP 1194, UDP 2200, SSL 992"
echo "   - Stunnel4                : 443"
echo "   - Dropbear                : 143, 109"
echo "   - Squid Proxy             : 3128, 8080 (limit to IP Server)"
echo "   - Badvpn                  : 7100, 7200, 7300"
echo "   - Wireguard               : 7070"
echo "   - L2TP/IPSEC VPN          : 1701"
echo "   - PPTP VPN                : 1732"
echo "   - SSTP VPN                : 5555"
echo "   - Shadowsocks-R           : 1443-1543"
echo "   - SS-OBFS TLS             : 2443-2543"
echo "   - SS-OBFS HTTP            : 3443-3453"
echo "   - V2RAY Vmess TLS         : 4443"
echo "   - V2RAY Vmess None TLS    : 80"
echo "   - Trojan                  : 6443"
echo "   OpenVPN Config : http://$IP/configs.zip"
echo "   Until On       : $(date -d "$aktif days" +"%d-%m-%Y")"
  echo "----------------------------------"
for (( i=1; i <= $banyakuser; i++ ))
do
	USER=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`
	useradd -M -N -s /bin/false -e $expire $USER
	PASS=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`;
	echo $USER:$USER | chpasswd
	echo "$i. Username/Password: $USER"
done

  echo "--------------------------------------"
  echo " "